version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
